version: '3.7'
services:
  mongo-seed:
    environment: 
      DB_HOST: mongo
      DB_NAME: db
      DB_PORT: 27017
      DROP_DATABASE: 'true'
      REPLACE_ID: 'true'
    build:
      context: ./packages/server/docker/env/artifacts/seed
      dockerfile: ./Dockerfile
    image: pkosiec/mongo-seeding
    networks:
      kodify-technical-test:
    depends_on:
      - 'mongo'
    volumes:
      - ./packages/server/docker/env/artifacts/seed/data/:/srv/import-data

  mongo:
    image: mongo:4.0.20@sha256:dd4cbe24eb8233db92b871cc556b77efcc7f9e67bc9516579796d4d08818273e
    networks:
      kodify-technical-test:
    ports:
      - 27017:27017
    volumes:
      - mongo_data_db:/data/db
      - mongo_data_config_db:/data/configdb

  client:
    tty: true
    environment:
      PORT: 3000
      NODE_ENV: 'develop'
      CHOKIDAR_USEPOLLING: 'true'
      DEBUG: '*'
    build:
      context: ./packages/client
      dockerfile: ./docker/env/artifacts/client/Dockerfile
    image: kodify-technical-test-client:latest
    networks:
      kodify-technical-test:
    ports:
      - 9227:9229
      - 3001:3000
    volumes:
      - ./packages/client:/srv/kodify-technical-test-client
      - node_modules_kodify-technical-test-client:/srv/kodify-technical-test-client/node_modules

  server:
    build:
      context: ./packages/server
      dockerfile: ./docker/env/artifacts/server/Dockerfile
    image: kodify-technical-test-server:latest
    networks:
      kodify-technical-test:
    ports:
      - 9228:9229
      - 3002:80
    volumes:
      - ./packages/server:/srv/kodify-technical-test-server
      - node_modules_kodify-technical-test-server:/srv/kodify-technical-test-server/node_modules

volumes:
  node_modules_kodify-technical-test-client:
  node_modules_kodify-technical-test-server:
  mongo_data_db:
  mongo_data_config_db:

networks:
  kodify-technical-test:
